Small update to readme
collectiveidea/awesome_nested_set pull request #458
Opened 2021-06-15 05:41 UTC by macarthy

Change the migration to more modern syntax 

def change etc .

2021-06-18 12:31 UTC, p8 requested changes

2021-06-18 12:31 UTC, p8 commented on README.md
> +
✂️ I think there is some redundant whitespace.
```suggestion
      t.integer :lft, null: false, index: true
      t.integer :rgt, null: false, index: true

```

2021-06-28 23:05 UTC, parndt commented on CHANGELOG
> +* Updated readme to use latest migration syntax
```suggestion
* Updated readme to use latest migration syntax [Justin MacCarthy](https://github.com/macarthy)
```

2021-06-28 23:41 UTC, parndt approved these changes

2021-06-28 23:43 UTC, merged